QuestRoom/Controllers/QuestRoomsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuestRoom.Data;
using QuestRoom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuestRoom.Controllers
{
    public class QuestRoomsController : Controller
    {
        private readonly QuestRoomContext context;

        //public BufferedMultipleFileUploadDb FileUpload { get; set; }

        public QuestRoomsController(QuestRoomContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var room = await context.Rooms.Include("Images").FirstOrDefaultAsync(r => r.Id == id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }
        //Отображение страници со всеми комнатами с возможностью фильтрации, многостраничности и поиска
        public async Task<IActionResult> Index(string SearchString, string[] difficulties, string[] Amount, string[] Fear, int? page)
        {
            if (SearchString != null)
            {
                page = 1;
            }
            var rooms = context.Rooms.Include("Images");

            List<Room> roomsList;
            if (!string.IsNullOrEmpty(SearchString))
            {
                rooms = rooms.Where(r => r.Name.Contains(SearchString));
                roomsList = await rooms.ToListAsync();
            }
            else
            {
                roomsList = await rooms.ToListAsync();
                if (difficulties.Length > 0)
                {
                    roomsList = roomsList.Where(r => difficulties.Contains(r.LevelOfDifficulty.ToString())).ToList();
                }
                if (Amount.Length > 0)
                {
                    int min = int.Parse(Amount[0]);
                    int max = int.Parse(Amount[1]);

                    roomsList = roomsList.Where(r => r.MinAmountOfPlayers >= min && r.MaxAmountOfPlayers <= max).ToList();
                }
                if (Fear.Length > 0)
                {
                    roomsList = roomsList.Where(r => Fear.Contains(r.LevelOfFear.ToString())).ToList();
                }
            }
            ViewData["CurrentSearch"] = SearchString;
            ViewData["CurrentDifficulty"] = difficulties;
            ViewData["CurrentAmount"] = Amount;
            ViewData["CurrentFear"] = Fear;

            int pageSize = 3;
            roomsList = roomsList.OrderBy(r => r.Name).ToList();
            return View(PaginatedList<Room>.Create(roomsList, page ?? 1, pageSize));
        }
    }
}

QuestRoom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuestRoom</title>
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/quest-rooms.css" />
    <link rel="stylesheet" href="~/css/quest-room.css">
    <link rel="stylesheet" href="~/css/photoswipe.css">
    <link rel="stylesheet" href="~/css/default-skin/default-skin.css">
</head>

<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="QuestRooms" asp-action="Index">QuestRoom</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QuestRooms" asp-action="Index">Home</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="space"></div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - QuestRoom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>